apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authority01

# Generamos un ConfigMap por cada ruta (cada uno tiene su propio en.json)
configMapGenerator:
  - name: onboarding-i18n
    files:
      - json/simpl-fe-onboarding/onboarding/en.json
  - name: identity-provider-i18n
    files:
      - json/simpl-fe-onboarding/identity-provider/en.json
  - name: simpl-shell-i18n
    files:
      - json/simpl-fe-onboarding/simpl-shell/en.json
  - name: sap-i18n
    files:
      - json/simpl-fe-onboarding/sap/en.json

# Parches que aplican los mounts al Deployment existente
patchesStrategicMerge:
  - patches/patch-simpl-fe-onboarding.yaml
